name: pocketbase_provider
description: Dart package which acts as a PocketBase data provider by exposing singleton.
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
 pocketbase: ^0.23.0

dev_dependencies:
  very_good_analysis: ^6.0.0